### ISSUE TITLE
Pomodoro app on startup.

### ISSUE THREAD

**Issue by Iysbaera** [codito/gnome-pomodoro#264] opened 2017-01-21 18:53 UTC
Hello, 
I installed pomodoro extension on Fedora 25, but on startup pomodoro app also starts. 
How can i disable pomodoro app on startup and leave only extension?

**Comment by smichel17** [comment] 2017-01-21 20:40
Duplicate of #249

**Comment by Iysbaera** [comment] 2017-01-21 20:44
> Duplicate of #249
Not at all. My issue is abosolutely different.

**Comment by smichel17** [comment] 2017-01-21 23:03
Oh, I misread the first time. My bad.

I'm a little confused by what you mean, though. Do you mean the pomodoro app opens a window on startup? This doesn't happen for me. If you open the gnome tweak tool and look under startup applications, is pomodoro listed there?

**Comment by Iysbaera** [comment] 2017-01-21 23:09
No, i checked later and there wasn't a pomodoro app in gnome-tweak-tool startup.
Pomodoro app not exactly opens, but i see it in my running applications tray at startup.

**Comment by kamilprusko** [comment] 2017-01-24 19:29
The extension checks status after startup, for instance to continue after reboot. For this it needs to access / start D-Bus service which is part of gnome-pomodoro. So the extension always starts the app, though without windows open it uses less resources. In latest version there is option to disable extension from the indicator so it won't autostart, though I added it mainly because under wayland there is no option to restart GNOME Shell in case of some issue.

![screenshot from 2017-01-24 20-11-58](https://cloud.githubusercontent.com/assets/1135423/22262664/19ba810e-e272-11e6-92eb-d388af31d555.png)

**Closed by kamilprusko** 2017-01-24 19:29 UTC
