### ISSUE TITLE
gnome-pomodoro fails to migrate its database

### ISSUE THREAD

**Issue by c-orlando** [codito/gnome-pomodoro#390] opened 2018-12-06 22:48 UTC
After running gnome-pomodoro for the second time, it throws the following error, and the stats become unavailable:
```
[username@arch ~]$ gnome-pomodoro

** (gnome-pomodoro:23675): CRITICAL **: 20:40:00.948: application.vala:308: Failed to migrate database: Error creating directory /home/username/.local/share/gnome-pomodoro: File exists

```
I already tried to reinstall it, I deleted the entire directory with rm -r, but if I open it twice the same problem happens.

OS: Arch Linux
Gnome version: 3.30.2-1

**Comment by linusheinz** [comment] 2018-12-27 11:09
Same here it appeared with the bump to new version of vala i think

**Comment by linusheinz** [comment] 2019-01-12 17:55
Duplicate of #380

**Closed** 2019-02-23 07:05 UTC
