### ISSUE TITLE
"unable to send notifications through org.freedesktop.Notifications"

### ISSUE THREAD

**Issue by thomai** [codito/gnome-pomodoro#284] opened 2017-03-13 11:58 UTC
I am using gnome-shell-pomodoro 0.13.1-1 as standalone application (not integrated in Gnome) and after some time it crashes with the warning

`(gnome-pomodoro:13463): GLib-GIO-WARNING **: unable to send notifications through org.freedesktop.Notifications: Timeout was reached
[1]    13463 segmentation fault (core dumped)  gnome-pomodoro`

I found a [similar warning in a project called revolt](https://github.com/aperezdc/revolt/issues/23) but I am not sure whether there is some relation.

Distribution: Arch
DE: Cinnamon 3.2.8

**Comment by thomai** [comment] 2017-03-13 13:59
I just found a stacktrace in my syslog which shows up when gnome-pomodoro crashes: http://pastebin.com/raw/6pzDB7jv

FYI: I tried the dev version as well by installing the [git-AUR package](https://aur.archlinux.org/packages/gnome-shell-pomodoro-git/). Same problem.

**Comment by kamilprusko** [comment] 2017-03-13 19:59
Thanks for the report.

The issue is between libgio and [cinnamon's notification daemon](https://github.com/linuxmint/Cinnamon/blob/master/js/ui/notificationDaemon.js). Maybe the timeout in libgio is caused by cinnamon closing connection prematurely or an exception in some handler? Try running cinnamon in commandline or check logs for cinnamon.

**Closed by kamilprusko** 2017-03-13 19:59 UTC

**Comment by thomai** [comment] 2017-03-16 15:45
No offense, but shouldn't gnome-pomodoro withstand an exception like that? I fully understand that the exception isn't the fault of gnome-pomodoro but IMHO this shouldn't end in a crash.

**Comment by kamilprusko** [comment] 2017-03-16 19:07
I know. There is no way to gracefully handle a segfault except when having a parent process or like in GNOME - by having an extension which could start the service again. Ideally, there should be an extension for Cinnamon too.

**Comment by stephan-dev** [comment] 2023-01-15 14:52
Hi, 2017. Who's here in 2023 via Google !?! Mint `19.3` LTS Cinnamon `4.4.8`
 In my `0.13.4` gnome-pomodoro version there's no crash anymore. Program works well on cinnamon except I never get any notifications at all, and I have the same error message in journald.

Workaround : desktop-portal ! => `$ GTK_USE_PORTAL=1 gnome-pomodoro`
Fixes notifications. But the buttons inside notifications (skip break, lengthen break, etc...) don't work.

Not related to segfault, but I post here because Google leads here for the error `unable to send notifications through org.freedesktop.Notifications: Timeout was reached`
