### ISSUE TITLE
Two Indicators in Ubuntu 17.10

### ISSUE THREAD

**Issue by KennyStier61** [codito/gnome-pomodoro#316] opened 2017-10-19 23:51 UTC
Running a fresh copy of Ubuntu 17.10 and installed this awesome extension with apt. Once I enabled it with the tweak tool, it gave me not one, but TWO pomodoro indicators. They work together (you play one, the other one mirrors it), but its unnecessary. This also means there are TWO overlays telling you to take a break/get to work. 

Both Indicators
![screenshot from 2017-10-19 23-50-00](https://user-images.githubusercontent.com/4749568/31799232-66e7e456-b528-11e7-8bf9-c1e403adec9c.png)

Indicator One Opened
![screenshot from 2017-10-19 23-50-24](https://user-images.githubusercontent.com/4749568/31799233-671289a4-b528-11e7-8420-883ea9849768.png)

Indicator Two Opened
![screenshot from 2017-10-19 23-50-36](https://user-images.githubusercontent.com/4749568/31799234-674120c0-b528-11e7-9aff-9b704a4b6b69.png)

**Comment by hanjiexi** [comment] 2017-10-20 14:22
This is because Ubuntu 17.10 now uses GNOME instead of Unity, and their customizations to GNOME include AppIndicator support, which can't be disabled unless you switch to a different desktop session as far as I can tell. So gnome-pomodoro, which was designed to support both Unity and GNOME, is loading both the AppIndicator and the GNOME extension.

My desktop actually crashed when I attempted to start/stop the pomodoro from the AppIndicator, but it continues to work fine when interacting with the GNOME extension.

**Comment by SaurabhMhaisekar** [comment] 2017-10-22 03:37
@KennyStier61 can you try building app from source. I just built applet from source and it is working fine for me.

**Comment by kamilprusko** [comment] 2017-10-22 14:06
Duplicate of #256 , so I'm closing this issue.

If it happens, restarting gnome-shell usually helps (Alt + F2, type "r")...

In master branch, it should be fixed for good. Thanks @SaurabhMhaisekar for confirming.

**Closed by kamilprusko** 2017-10-22 14:06 UTC
