### ISSUE TITLE
Freeze when in a file dialog when "time to take a break" message comes

### ISSUE THREAD

**Issue by paul4forest** [codito/gnome-pomodoro#261] opened 2017-01-11 11:00 UTC
I am using a pomodoro version installed recently from github (10 days ago). It has been working great over this period. Except when the "take a break" message comes while I am in a file dialogue. I mean the "save a copy" type of dialogue where you have to choose a directory and file name.  If I continue typing in the file dialogue, the screen freezes, the top bar, calendar and pomodoro menu still work but there is no mouse or keyboard access to any other program. The issue only happens when the file dialogue is already open when the "take a break" message appears.

I don't know if this matters, now this happened while I was saving a file in Jabref, a Java based reference management system. Or maybe I was saving a PDF file under a new name with evince, I don't remember exactly which of the 2.

I am using Gnome on Debian 8 Jessie.

**Comment by kamilprusko** [comment] 2017-01-12 19:09
Duplicate of #190

Thanks for reporting this is still the issue. Issue is reported on [gnome-shell bugzilla](https://bugzilla.gnome.org/show_bug.cgi?id=754102) and needs love.

**Closed by kamilprusko** 2017-01-12 19:09 UTC

**Comment by paul4forest** [comment] 2017-01-12 20:33
Thanks, yes the issue is similar to  #190. It is hard to reproduce but annoying when it does happen.
