### ISSUE TITLE
Gnome shell killed by signal 11 when short break is announced

### ISSUE THREAD

**Issue by nikobreu** [codito/gnome-pomodoro#255] opened 2016-12-16 20:05 UTC
I enjoy your program. Unfortunately there is an issue on my desktop machine.
The moment the notification for a short break pops up the gnome-shell is being killed.
When I log back in it the same error occurs.

Here is the excerpt from the log file:
> Dec 16 18:40:45 homebox-linux kernel: gnome-shell[17092]: segfault at 8 ip 00007fb666fd54c3 sp 00007ffed1ec1de8 error 4 in libc-2.24.so[7fb666e86000+1bd000]
Dec 16 18:40:45 homebox-linux abrt-hook-ccpp[17416]: Process 17092 (gnome-shell) of user 1000 killed by SIGSEGV - ignoring (repeated crash)
Dec 16 18:40:45 homebox-linux gnome-pomodoro[17167]: Error reading events from display: Broken pipe
Dec 16 18:40:45 homebox-linux evolution-alarm[17252]: Error reading events from display: Broken pipe
Dec 16 18:40:45 homebox-linux gnome-software[17241]: Error reading events from display: Broken pipe
Dec 16 18:40:45 homebox-linux unknown[17248]: Error reading events from display: Broken pipe
Dec 16 18:40:45 homebox-linux org.gnome.Shell.desktop[17092]: (EE)
Dec 16 18:40:45 homebox-linux org.gnome.Shell.desktop[17092]: Fatal server error:
Dec 16 18:40:45 homebox-linux org.gnome.Shell.desktop[17092]: (EE) failed to read Wayland events: Broken pipe
Dec 16 18:40:45 homebox-linux org.gnome.Shell.desktop[17092]: (EE)
Dec 16 18:40:45 homebox-linux polkitd[1180]: Unregistered Authentication Agent for unix-session:20 (system bus name :1.312, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_GB.UTF-8) (disconnected from bus)
Dec 16 18:40:45 homebox-linux gnome-session[17072]: gnome-session-binary[17072]: WARNING: Application 'org.gnome.Shell.desktop' killed by signal 11

**Comment by kamilprusko** [comment] 2016-12-16 20:18
Hi @nikobreu,

Do segfault happens also for other notifications? Traceback seems to be related to Wayland and perhaps to a notification baner. Do you run development / testing version of gnome-shell / OS?

It would really help to run gnome-shell in gdb (https://wiki.gnome.org/Projects/GnomeShell/Debugging), and get a backtrace.

**Comment by kamilprusko** [comment] 2016-12-16 22:16
Seems this issue is reported upstream (I don't reproduce it)
https://bugzilla.gnome.org/show_bug.cgi?id=773928

**Comment by nikobreu** [comment] 2016-12-17 08:31
All right then.
Thanks for the quick response!

Cheers

**Comment by kamilprusko** [comment] 2017-02-20 21:43
Closing. It doesn't look to be issue caused by Pomodoro.

**Closed by kamilprusko** 2017-02-20 21:43 UTC
