### ISSUE TITLE
Notification change the system volume every time.

### ISSUE THREAD

**Issue by aerostitch** [codito/gnome-pomodoro#244] opened 2016-10-17 00:11 UTC
Hi @kamilprusko ,

It seems that whenever the application triggers a sound, it changes the volume of the entire system to what the sound level of the notification is set to.
Even in the preferences, if you go from one sound of bell to another, it changes the system volume level.

This can be problematic when you have headphones and a quite loud song! :)

Is it possible to change that?
It has been reported here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=838573

Thanks for your help,
Joseph

**Comment by bndo2** [comment] 2016-10-17 06:02
I could not duplicate this issue with gnome-pomodoro 0.12.2 with gnome-shell 3.22 and pulseaudio 9.0.

**Comment by kamilprusko** [comment] 2016-10-17 07:21
Hi @aerostitch 

I don't think that apps using pulseaudio can override system volume - it's by design, it was one of the benefits over ALSA (maybe he or some of the libraries doesn't use pulse?).

For notifications Pomodoro uses libcanberra, I could try gstreamer if I start reproducing the issue. Internally Pomodoro does equivalent to this

    $ canberra-gtk-play --id=complete --volume=1.0

I'll keep my eye on it, but more likely it's a system-wide issue.

**Comment by ukch** [comment] 2016-10-17 08:39
Hi @kamilprusko - I'm the original reporter of this bug, on Debian.
So I don't know what the code was doing in the past, but this has only been an issue for me since I upgraded Pomodoro to the latest version (sorry, I don't remember what version I was using before).
The original version played the sound at whatever the system volume was set to - I don't think it was configurable in the preferences - and did not have this issue.

**Comment by aerostitch** [comment] 2016-10-17 14:33
I wonder if this could be linked to gnome 3.21 / 3.22.
When I check also with `pactl list` I see the following:
```
Sample #0
	Name: bell-window-system
	Sample Specification: s16le 2ch 44100Hz
	Channel Map: front-left,front-right
	Volume: (invalid)
	        balance 0.00
	Duration: 0.1s
	Size: 24.0 KiB
	Lazy: no
	Filename: n/a
	Properties:
		media.role = "event"
		application.process.id = "3886"
		application.name = "gnome-terminal-server"
		event.description = "Bell event"
		event.id = "bell-window-system"
		media.name = "bell-window-system"
		media.filename = "/usr/share//sounds/freedesktop/stereo/bell.oga"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "31"
		application.id = "org.gnome.Shell"
		application.icon_name = "start-here"
		application.language = "en_US.utf8"
		window.x11.screen = "0"
		window.x11.display = ":0"
		application.process.user = "theolediable"
		application.process.host = "d01"
		application.process.binary = "gnome-shell"
		application.process.machine_id = "6fd64dc0f9b94e9f84cae0ca3f5448b7"
		application.process.session_id = "2"

Sample #1
	Name: audio-volume-change
	Sample Specification: s16le 2ch 44100Hz
	Channel Map: front-left,front-right
	Volume: (invalid)
	        balance 0.00
	Duration: 0.1s
	Size: 11.5 KiB
	Lazy: no
	Filename: n/a
	Properties:
		media.role = "event"
		event.description = "volume changed through key press"
		event.id = "audio-volume-change"
		media.name = "audio-volume-change"
		media.filename = "/usr/share//sounds/freedesktop/stereo/audio-volume-change.oga"
		application.name = "libcanberra"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "31"
		application.version = "0.30"
		application.id = "org.freedesktop.libcanberra"
		application.process.id = "3620"
		application.process.user = "theolediable"
		application.process.host = "d01"
		application.process.binary = "gnome-settings-daemon (deleted)"
		application.language = "en_US.utf8"
		window.x11.display = ":0"
		application.process.machine_id = "6fd64dc0f9b94e9f84cae0ca3f5448b7"
		application.process.session_id = "2"

Sample #2
	Name: pomodoro-0
	Sample Specification: s16le 2ch 44100Hz
	Channel Map: front-left,front-right
	Volume: (invalid)
	        balance 0.00
	Duration: 1.1s
	Size: 187.6 KiB
	Lazy: no
	Filename: n/a
	Properties:
		media.role = "event"
		media.filename = "/usr/share/gnome-pomodoro/sounds/loud-bell.ogg"
		event.id = "pomodoro-0"
		media.name = "pomodoro-0"
		application.name = "gnome-pomodoro"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "31"
		application.id = "org.gnome.Pomodoro"
		application.icon_name = "gnome-pomodoro"
		application.process.id = "25726"
		application.process.user = "theolediable"
		application.process.host = "d01"
		application.process.binary = "gnome-pomodoro"
		application.language = "en_US.utf8"
		window.x11.display = ":0"
		application.process.machine_id = "6fd64dc0f9b94e9f84cae0ca3f5448b7"
		application.process.session_id = "2"

Sample #3
	Name: pomodoro-1
	Sample Specification: s16le 2ch 44100Hz
	Channel Map: front-left,front-right
	Volume: (invalid)
	        balance 0.00
	Duration: 0.2s
	Size: 41.8 KiB
	Lazy: no
	Filename: n/a
	Properties:
		media.role = "event"
		media.filename = "/usr/share/gnome-pomodoro/sounds/bell.ogg"
		event.id = "pomodoro-1"
		media.name = "pomodoro-1"
		application.name = "gnome-pomodoro"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "31"
		application.id = "org.gnome.Pomodoro"
		application.icon_name = "gnome-pomodoro"
		application.process.id = "25726"
		application.process.user = "theolediable"
		application.process.host = "d01"
		application.process.binary = "gnome-pomodoro"
		application.language = "en_US.utf8"
		window.x11.display = ":0"
		application.process.machine_id = "6fd64dc0f9b94e9f84cae0ca3f5448b7"
		application.process.session_id = "2"

Sample #4
	Name: pomodoro-2
	Sample Specification: s16le 2ch 44100Hz
	Channel Map: front-left,front-right
	Volume: (invalid)
	        balance 0.00
	Duration: 0.2s
	Size: 41.8 KiB
	Lazy: no
	Filename: n/a
	Properties:
		media.role = "event"
		media.filename = "/usr/share/gnome-pomodoro/sounds/bell.ogg"
		event.id = "pomodoro-2"
		media.name = "pomodoro-2"
		application.name = "gnome-pomodoro"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "31"
		application.id = "org.gnome.Pomodoro"
		application.icon_name = "gnome-pomodoro"
		application.process.id = "25726"
		application.process.user = "theolediable"
		application.process.host = "d01"
		application.process.binary = "gnome-pomodoro"
		application.language = "en_US.utf8"
		window.x11.display = ":0"
		application.process.machine_id = "6fd64dc0f9b94e9f84cae0ca3f5448b7"
		application.process.session_id = "2"

Sample #5
	Name: pomodoro-3
	Sample Specification: s16le 2ch 44100Hz
	Channel Map: front-left,front-right
	Volume: (invalid)
	        balance 0.00
	Duration: 0.2s
	Size: 41.8 KiB
	Lazy: no
	Filename: n/a
	Properties:
		media.role = "event"
		media.filename = "/usr/share/gnome-pomodoro/sounds/bell.ogg"
		event.id = "pomodoro-3"
		media.name = "pomodoro-3"
		application.name = "gnome-pomodoro"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "31"
		application.id = "org.gnome.Pomodoro"
		application.icon_name = "gnome-pomodoro"
		application.process.id = "25726"
		application.process.user = "theolediable"
		application.process.host = "d01"
		application.process.binary = "gnome-pomodoro"
		application.language = "en_US.utf8"
		window.x11.display = ":0"
		application.process.machine_id = "6fd64dc0f9b94e9f84cae0ca3f5448b7"
		application.process.session_id = "2"

Sample #6
	Name: pomodoro-4
	Sample Specification: s16le 2ch 44100Hz
	Channel Map: front-left,front-right
	Volume: (invalid)
	        balance 0.00
	Duration: 0.2s
	Size: 41.8 KiB
	Lazy: no
	Filename: n/a
	Properties:
		media.role = "event"
		media.filename = "/usr/share/gnome-pomodoro/sounds/bell.ogg"
		event.id = "pomodoro-4"
		media.name = "pomodoro-4"
		application.name = "gnome-pomodoro"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "31"
		application.id = "org.gnome.Pomodoro"
		application.icon_name = "gnome-pomodoro"
		application.process.id = "25726"
		application.process.user = "theolediable"
		application.process.host = "d01"
		application.process.binary = "gnome-pomodoro"
		application.language = "en_US.utf8"
		window.x11.display = ":0"
		application.process.machine_id = "6fd64dc0f9b94e9f84cae0ca3f5448b7"
		application.process.session_id = "2"

Sample #7
	Name: pomodoro-5
	Sample Specification: s16le 2ch 44100Hz
	Channel Map: front-left,front-right
	Volume: (invalid)
	        balance 0.00
	Duration: 0.2s
	Size: 41.8 KiB
	Lazy: no
	Filename: n/a
	Properties:
		media.role = "event"
		media.filename = "/usr/share/gnome-pomodoro/sounds/bell.ogg"
		event.id = "pomodoro-5"
		media.name = "pomodoro-5"
		application.name = "gnome-pomodoro"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "31"
		application.id = "org.gnome.Pomodoro"
		application.icon_name = "gnome-pomodoro"
		application.process.id = "25726"
		application.process.user = "theolediable"
		application.process.host = "d01"
		application.process.binary = "gnome-pomodoro"
		application.language = "en_US.utf8"
		window.x11.display = ":0"
		application.process.machine_id = "6fd64dc0f9b94e9f84cae0ca3f5448b7"
		application.process.session_id = "2"

Sample #8
	Name: pomodoro-6
	Sample Specification: s16le 2ch 44100Hz
	Channel Map: front-left,front-right
	Volume: (invalid)
	        balance 0.00
	Duration: 1.1s
	Size: 187.6 KiB
	Lazy: no
	Filename: n/a
	Properties:
		media.role = "event"
		media.filename = "/usr/share/gnome-pomodoro/sounds/loud-bell.ogg"
		event.id = "pomodoro-6"
		media.name = "pomodoro-6"
		application.name = "gnome-pomodoro"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "31"
		application.id = "org.gnome.Pomodoro"
		application.icon_name = "gnome-pomodoro"
		application.process.id = "25726"
		application.process.user = "theolediable"
		application.process.host = "d01"
		application.process.binary = "gnome-pomodoro"
		application.language = "en_US.utf8"
		window.x11.display = ":0"
		application.process.machine_id = "6fd64dc0f9b94e9f84cae0ca3f5448b7"
		application.process.session_id = "2"

Sample #9
	Name: pomodoro-7
	Sample Specification: s16le 2ch 44100Hz
	Channel Map: front-left,front-right
	Volume: (invalid)
	        balance 0.00
	Duration: 0.2s
	Size: 41.8 KiB
	Lazy: no
	Filename: n/a
	Properties:
		media.role = "event"
		media.filename = "/usr/share/gnome-pomodoro/sounds/bell.ogg"
		event.id = "pomodoro-7"
		media.name = "pomodoro-7"
		application.name = "gnome-pomodoro"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "31"
		application.id = "org.gnome.Pomodoro"
		application.icon_name = "gnome-pomodoro"
		application.process.id = "25726"
		application.process.user = "theolediable"
		application.process.host = "d01"
		application.process.binary = "gnome-pomodoro"
		application.language = "en_US.utf8"
		window.x11.display = ":0"
		application.process.machine_id = "6fd64dc0f9b94e9f84cae0ca3f5448b7"
		application.process.session_id = "2"

Sample #10
	Name: pomodoro-8
	Sample Specification: s16le 2ch 44100Hz
	Channel Map: front-left,front-right
	Volume: (invalid)
	        balance 0.00
	Duration: 1.1s
	Size: 187.6 KiB
	Lazy: no
	Filename: n/a
	Properties:
		media.role = "event"
		media.filename = "/usr/share/gnome-pomodoro/sounds/loud-bell.ogg"
		event.id = "pomodoro-8"
		media.name = "pomodoro-8"
		application.name = "gnome-pomodoro"
		native-protocol.peer = "UNIX socket client"
		native-protocol.version = "31"
		application.id = "org.gnome.Pomodoro"
		application.icon_name = "gnome-pomodoro"
		application.process.id = "25726"
		application.process.user = "theolediable"
		application.process.host = "d01"
		application.process.binary = "gnome-pomodoro"
		application.language = "en_US.utf8"
		window.x11.display = ":0"
		application.process.machine_id = "6fd64dc0f9b94e9f84cae0ca3f5448b7"
		application.process.session_id = "2"
```
And I wonder if the `Volume: (invalid)` could be the cause of the issue.
Not an expert in pulseaudio though.

**Comment by kamilprusko** [comment] 2016-10-17 23:00
I think that ```Volume: (invalid)``` is just not an available property for samples. Checked on older system - it's there too.

Found this tip on https://bugs.freedesktop.org/show_bug.cgi?id=97352
> Did you set "flat-volumes = no" in ~/.config/pulse/daemon.conf? When flat volumes are enabled, hardware volume is affected by stream volumes, but when disabled, there should be no such coupling.

@ukch Or maybe this seem bug seem related? https://bugs.freedesktop.org/show_bug.cgi?id=93010

I've tried to reproduce it on Ubuntu 16.10 with pulseaudio 9.0.0. Notifications do not play unless they are at 100% in pomodoro settings and ```canberra-gtk-play``` does not work at all... I'll try to debug it and report upstream. I didn't reproduce your issue though.

**Comment by kamilprusko** [comment] 2016-11-01 16:15
I'll close it for now because I don't reproduce it, and as pomodoro doesn't deal with pulseaudio directly it's more likely that the issue is elsewhere.

Fixed issue with volume slider in c72317396a96ad89470ab512795131a6bd379606.

**Closed by kamilprusko** 2016-11-01 16:15 UTC

**Comment by ghisvail** [comment] 2018-01-29 17:12
Same here on a Debian Buster machine. You can install the `gnome-shell-pomodoro` package, start the timer, turn the volume to half and wait until the start bell rings. The volume slider gets back to the maximum.

This can get quite uncomfortable depending on your audio setup. I consider this a major usability issue. Please keep this issue open.

**Comment by oli-obk** [comment] 2018-03-20 10:15
I also encountered this. Setting the start/end sound volume with the sliders works as a workaround (the gobal sound volume is changed to around twice the setting of the start/end sound volume), but it's still suboptimal.

**Comment by ghisvail** [comment] 2018-03-20 11:02
Sadly, I had to stop using the extension eventually as the sudden full-volume bings were really uncomfortable, if not hurting sometimes, whilst using my headphones.

> Setting the start/end sound volume with the sliders works as a workaround [...] but it's still suboptimal.

I second the opinion that the manual slider is not a suitable solution. Any user installing this extension for the first time and experiencing this issue will likely just drop it and not bother checking the issue tracker for a possible workaround using the sliders.

**Comment by thrnio** [comment] 2018-03-29 23:20
If flat-volume is enabled (which is the PulseAudio default, although many distros override that because it's an insane default for this and other reasons), then if an application sets a volume level higher than the current system volume level, then PulseAudio raises the system volume to match that level.

**Comment by egesu** [comment] 2018-07-20 14:51
Experiencing exact same issue on Gnome 3.28.

**Comment by mbboc** [comment] 2019-08-31 17:55
Hi,
I am experiencing the same issue, also since at least last year. (I stopped using it, but tried now again)

To narrow it down: I can reproduce it by playing around with the sound settings in the menu. 

1. The system-volume changing behaviour goes only in one direction: louder
2. If the system volume is e.g. 100 and one turns down the alarm-volume, it doesn't change system-volume. The alarm-sound plays as more quiet as intended.
3. The alarm-volume and system sound doesn't match each other after pomodoro affects system-volume.  
alarm-sound vol 25% -> system volume ca. 60% 
alarm-sound vol 50% -> system volume ca. 80%
alarm-sound vol 75% -> system volume ca. 95% 
(non-linear)
4. it doesn't matter how much system volume was before. it always sets as described above except 0
5. It doesnt turn the sound on, when system sound is off.
6. it doesn't matter which alarm-sound (loudbell vs bell)
7. It is the only application on my machine that affects the system sound in this strange manner. 

Ubuntu 19.04 5.0.0-25-generic #26-Ubuntu SMP Thu Aug 1 12:04:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
pulseaudio 12.2
GNOME Shell 3.32.2 
only extension on while testing was gnome-pomodoro 0.15.2

I am using it now with very low sound volume. But it still affects the system sound only. This means I have to go into pulseaudiosettings (pavu-control) and turn up the volumes of every other application. 

Please open the issue again. thx michael
