### ISSUE TITLE
Idea: script hooks

### ISSUE THREAD

**Issue by v-for-vincent** [codito/gnome-pomodoro#118] opened 2013-12-19 15:49 UTC
I get the impression a lot of features that might be requested could be handled by providing a plugin or script hook mechanism. Possible use cases include keeping track of the work you've done in an arbitrary timesheet app, locking/unlocking particular applications, etc.

**Comment by kamilprusko** [comment] 2016-09-09 17:26
Duplicate of #70 

As of now there is plugin engine (based on libpeas) and D-Bus interface. A plugin for script hooks is on its way.

**Closed by kamilprusko** 2016-09-09 17:26 UTC
