### ISSUE TITLE
Pomodoro doesn't show break timer on Fedora 29 and GNOME 3.30 via extension

### ISSUE THREAD

**Issue by Novined** [codito/gnome-pomodoro#385] opened 2018-11-10 13:58 UTC
After update I have that issue. When I break is starts there are no timer, but screen is locked (I need a click to unlock). Without extension timer is ok, but system panels become hidden. I even tried to install pomodoro on F29 GNOME Live Disk. There I have the same issue.
Behaviour via extension https://www.youtube.com/watch?v=oMmWJeJsg2Q
Without extension https://www.youtube.com/watch?v=gC9_TSg4Ryo https://imgur.com/nabjyc5

**Comment by junrrein** [comment] 2018-11-12 19:56
I can reproduce this issue. Also Fedora 29 and Gnome 3.30, using the shell extension.

**Comment by hectorakemp** [comment] 2018-12-03 23:18
Ditto on this issue. Fedora 29 and Gnome 3.3

**Comment by junrrein** [comment] 2018-12-13 22:08
This was fixed in version 0.14, which as of today has been already uploaded to the Fedora 29 repos. Feel free to close.

**Comment by szpak** [comment] 2018-12-13 22:21
I've been using 0.14 in Fedora 29 for a few days and I the problem seems to be solved.

**Closed** 2018-12-14 04:53 UTC
