### ISSUE TITLE
Problem with notification start break sound

### ISSUE THREAD

**Issue by krchat** [codito/gnome-pomodoro#291] opened 2017-04-09 07:24 UTC
Fedora 25. I checked my system settings
$ canberra-gtk-play --file=/usr/share/gnome-pomodoro/sounds/loud-bell.ogg --volume=1.0
the sound - On.
I added my ogg file to Start Break sound. If I click on it - it plays well, but sound doesn't start from pomodoro timer.

**Comment by kamilprusko** [comment] 2017-04-09 09:03
It keeps playing the default sound. Thanks for the report.

**Comment by krchat** [comment] 2017-04-09 09:33
but how can I set my own sound?

**Comment by kamilprusko** [comment] 2017-04-09 09:35
I'll make a patch. It doesn't look that while playing the sound it sees the setting.

**Comment by krchat** [comment] 2017-04-09 10:07
Thanks, I used to try it half of previous night, thinking about my errors of setting or working system. 
I'm waiting for news about it.

**Comment by kamilprusko** [comment] 2017-05-07 15:14
The issue is with updating the sound in canberra/pulseaudio cache. You could may it by

    $ pactl remove-sample pomodoro-start
    $ pactl remove-sample pomodoro-end

Fixed in 0.13.2

**Closed by kamilprusko** 2017-05-07 15:14 UTC
